name: Hello World!

on:
    push:
        branches:
            - master


jobs:
    hello_world_job:
        run_on: ubuntu-20.04
        steps:
            - name: Say Hello
              run: |
                  echo "Hello World!"
